import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from 'next-auth/react'

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        status === 'authenticated' && <div>
          <h1>Logged in as <span style={{ color: "blue" }}>{session?.user?.name}</span></h1>
          <div style={{
            alignItems: "center",
            display: "flex",
          }}>
            <Image
              src={session?.user?.image || ""}
              alt="Picture of the user"
              width={100}
              height={100}
              style={{
                borderRadius: "20px",
              }}
            />
            <button style={{
              padding: "10px",
              margin: "10px 30px",
              borderRadius: "5px",
              fontSize: "20px",
              fontWeight: "bold",
            }}
              onClick={() => signOut()}
            >Logout</button>
          </div>
        </div>
      }
      {
        status === 'unauthenticated' && <div>
          <h1>You are not logged in</h1>
          <button style={{
            padding: "10px",
            margin: "10px 30px",
            borderRadius: "5px",
            fontSize: "20px",
            fontWeight: "bold",
          }}
            onClick={() => signIn()}
          >Login</button>
        </div>
      }


    </div>
  )
}
